---
- name: Deploy helper scripts
  template:
    src: "restic-helper.j2"
    dest: "{{ restic_helper_dir }}/restic-{{ item.name }}"
    mode: "{{ restic_helper_mode }}"
  with_items: '{{ restic_repositories }}'
  when: restic_helpers_enable

- name: Init repositories
  command: "{{ restic_bin_dir }}/restic init"
  environment: "{{ item.environment | d({}) | combine({'RESTIC_PASSWORD': item.password | trim | quote, 'RESTIC_REPOSITORY': item.url | trim | quote}) }}"
  no_log: false
  register: __restic_repo_init
  changed_when: "'created restic repository' in __restic_repo_init.stdout"
  failed_when:
    - __restic_repo_init.rc != 0
    - not 'config already initialized' in __restic_repo_init.stderr
  with_items: '{{ restic_repositories }}'
  when: item.init is defined and item.init

- name: Deploy cron script
  template:
    src: "restic.cron.j2"
    dest: "/etc/cron.d/restic-{{ item.name }}"
    mode: "0640"
  no_log: false
  with_items: "{{ restic_repositories }}"